export const faqDatabase = {
    general: {
      ar: {
        'إيه مواعيد الاختبارات؟': 'الاختبارات يوم 15 مايو الساعة 10 صباحًا يا جميل!',
        'متى الامتحانات؟': 'الامتحانات هتبقى يوم 15 مايو الساعة 10 صباحًا، يلا استعد!',
        'كيف ادخل على المنصة؟': 'ادخل من الموقع الرئيسي سكيب واستخدم ايميلك وكلمة المرور، سهلة يا بطل!',
        'فين المواد الدراسية؟': 'المواد في قسم المواد من القايمة، روح شوفها!',
        'المنصة بتشتغل ازاي؟': 'المنصة بسيطة، اختار قسم زي المواد أو الاختبارات وابدأ التعلم!',
        'هل المنصة مجانية؟': 'ايوه مجانية، بس فيه ميزات إضافية بتجي مع الاشتراك!',
        'كيف أسجل حساب؟': 'اضغط على تسجيل الدخول واملأ البيانات، وخلّص!',
        'فين القايمة؟': 'القايمة تظهر لما تضغط على أيقونة المينيو في الأعلى!',
        'الدروس متين بتتحدث؟': 'الدروس بتتحدث يوميًا، تابع الجدول في قسم المواد!',
        'كيف أسأل سؤال؟': 'اكتب سؤالك هنا في الشات وهنجاوبك فورًا يا حبيبي!',
        'إيه أفضل طريقة للدراسة؟': 'جرب تذاكر بالتدريج وخد فترات راحة، هتفيدك كتير!',
        'فين نتايج الاختبارات؟': 'النتايج هتبقى في قسم النتايج بعد التصحيح!',
        'كيف أغير اللغة؟': 'اضغط على زر اللغة في الأسفل واختار عربي أو إنجليزي!',
        'الدعم متوفر متي؟': 'الدعم متوفر 24/7، ارسل سؤالك وهنرد فورًا!',
        'فين الدروس التسجيلية؟': 'الدروس التسجيلية في قسم المواد تحت فيديوهات!',
        'كيف أشارك في المناقشات؟': 'ادخل قسم المناقشات واضغط على بدء موضوع جديد!',
        'المنصة تدعم موبايل؟': 'ايوه، المنصة مظبوطة على الموبايل والكمبيوتر!',
        'متي بيظهر جدول المواد؟': 'الجدول بيظهر كل اسبوع في قسم الاعلانات!',
        'كيف أحمل المواد؟': 'اضغط على المادة واختار خيار التحميل لو متاح!',
        'هل فيه اختبارات أسبوعية؟': 'ايوه، فيه اختبارات أسبوعية، تابع الجدول!',
        'المنصة آمنة؟': 'ايوه، المنصة آمنة ومحمية بأعلى معايير الأمان!',
        'كيف أنسى كلمة المرور؟': 'اضغط على نسيت كلمة المرور واتبع الخطوات!',
        'فين قسم الأسئلة الشائعة؟': 'في الأسفل في الفوتر، اضغط على FAQ!',
        'الدروس بتتجدد؟': 'ايوه، الدروس بتتجدد كل شهر، تابع التحديثات!',
        'كيف أتواصل مع المعلمين؟': 'من قسم المناقشات أو ارسل ايميل للدعم!',
        'المنصة بتدعم اندرويد؟': 'ايوه، فيه تطبيق للاندرويد، حمل من متجر التطبيقات!',
        'متي الدروس المباشرة؟': 'الدروس المباشرة بتبدأ الساعة 8 مساءً يوميًا!',
        'كيف أعرف درجاتي؟': 'ادخل قسم النتايج وشوف درجاتك النهائية!',
        'فين فيديوهات الشرح؟': 'في قسم المواد تحت كل درس!',
        'الدعم بيرد بالعامية؟': 'ايوه، ممكن نرد بالعامية لو عايز، قول لنا!',
      },
      en: {
        'What are the exam dates?': 'The exams are on May 15th at 10 AM, buddy!',
        'When are the exams?': 'Exams will be on May 15th at 10 AM, get ready!',
        'How do I log in to the platform?': 'Log in from the main Skip site with your email and password, easy peasy!',
        'Where are the study materials?': 'Materials are in the Materials section from the menu, check it out!',
        'How does the platform work?': 'It’s simple, pick a section like Materials or Quizzes and start learning!',
        'Is the platform free?': 'Yes, it’s free, but some extras come with a subscription!',
        'How do I create an account?': 'Click Sign In and fill in your details, done!',
        'Where is the menu?': 'The menu pops up when you click the menu icon up top!',
        'When are the lessons updated?': 'Lessons are updated daily, check the schedule in Materials!',
        'How do I ask a question?': 'Type your question here in the chat, and we’ll reply fast, champ!',
        'What’s the best study method?': 'Try studying gradually with breaks, it works wonders!',
        'Where are the exam results?': 'Results will be in the Results section after grading!',
        'How do I change the language?': 'Click the language button below and choose Arabic or English!',
        'When is support available?': 'Support is 24/7, send your question and we’ll reply fast!',
        'Where are the recorded lessons?': 'Recorded lessons are in the Materials section under videos!',
        'How do I join discussions?': 'Go to Discussions and click Start New Topic!',
        'Does the platform support mobile?': 'Yes, it works great on mobile and PC!',
        'When is the materials schedule out?': 'The schedule is out weekly in the Announcements section!',
        'How do I download materials?': 'Click the material and select Download if available!',
        'Are there weekly exams?': 'Yes, there are weekly exams, check the schedule!',
        'Is the platform secure?': 'Yes, it’s secure with top safety standards!',
        'What if I forget my password?': 'Click Forgot Password and follow the steps!',
        'Where is the FAQ section?': 'It’s in the footer below, click FAQ!',
        'Are lessons updated?': 'Yes, lessons are updated monthly, stay tuned!',
        'How do I contact teachers?': 'Via Discussions or email support!',
        'Does it support Android?': 'Yes, there’s an Android app, download from the store!',
        'When are live lessons?': 'Live lessons start at 8 PM daily!',
        'How do I check my grades?': 'Go to Results and see your final grades!',
        'Where are the explanation videos?': 'In the Materials section under each lesson!',
        'Does support use slang?': 'Yes, we can use slang if you want, just ask!',
      }
    },
    studies: {
      ar: {
        'إيه أهم مواضيع الدراسات؟': 'أهم المواضيع هي التاريخ والجغرافيا، ركز عليهم يا زعيم!',
        'كيف أذاكر الدراسات؟': 'اقسم المنهج لأجزاء وكرر كل يوم، هتفضل ذكي!',
        'فين ملخصات الدراسات؟': 'الملخصات في قسم المواد تحت مادة الدراسات!',
        'متي امتحان الدراسات؟': 'امتحان الدراسات يوم 15 مايو الساعة 10 صباحًا!',
        'إيه أصعب جزء في الدراسات؟': 'الجغرافيا بتكون صعبة شوية، لكن مع المراجعة هتبقى أسهل!',
        'كيف أفهم التاريخ؟': 'اقرأ القصص وربط بين الأحداث، هتفهم كده يا أستاذ!',
        'فين أسئلة سابقة الدراسات؟': 'في قسم الاختبارات تحت أسئلة سابقة!',
        'هل الدراسات فيها فيديوهات؟': 'ايوه، فيه فيديوهات شرح في قسم المواد!',
        'كيف أحسن درجاتي في الدراسات؟': 'حل أسئلة كتير وحضر الدروس المباشرة!',
        'إيه أفضل كتاب للدراسات؟': 'كتاب المنهج الرسمي هو الأفضل، استخدمه يا بطل!',
        'متي بتظهر دروس الدراسات؟': 'الدروس بتظهر يوميًا في قسم المواد!',
        'فين خرائط الجغرافيا؟': 'الخرائط في قسم الدراسات تحت الجغرافيا!',
        'كيف أذاكر الحروب؟': 'اكتب ملخص لكل حرب وكرر، هتتذكر كده!',
        'هل فيه امتحان أونلاين للدراسات؟': 'ايوه، فيه امتحان أونلاين، تابع الجدول!',
        'إيه أهمية الدراسات؟': 'الدراسات بتعلّمك تاريخ بلدك، مهمة جدًا يا صديق!',
        'كيف أحل أسئلة الجغرافيا؟': 'ركز على الخرائط واعمل مراجعة يومية!',
        'فين دروس التاريخ؟': 'في قسم المواد تحت مادة الدراسات!',
        'متي الدروس المباشرة للدراسات؟': 'الدروس المباشرة بتبدأ 8 مساءً!',
        'كيف أفهم الاقتصاد؟': 'شوف الفيديوهات والملخصات، هتبقى واضحة!',
        'هل الدراسات صعبة؟': 'محدش بيقول إنها سهلة، لكن مع المجهود هتبقى كده!',
        'فين امتحانات نصف السنة؟': 'في قسم الاختبارات تحت الدراسات!',
        'كيف أذاكر للامتحان النهائي؟': 'راجع كل الملخصات واعمل أسئلة!',
        'إيه أفضل طريقة للخرائط؟': 'ارسم الخرائط بنفسك، هتتذكرها أكتر!',
        'فين دروس الجغرافيا؟': 'في قسم المواد تحت الدراسات!',
        'كيف أحسن كتابتي في الدراسات؟': 'اكتب إجابات قصيرة وواضحة!',
        'هل فيه كتب إضافية؟': 'ايوه، فيه كتب في قسم المواد!',
        'متي نتايج الدراسات؟': 'النتايج بعد التصحيح في قسم النتايج!',
        'كيف أحضر للامتحان؟': 'خد ملخصات واعمل اختبارات تجريبية!',
        'فين أمثلة الإجابات؟': 'في قسم الاختبارات تحت الدراسات!',
        'إيه أسهل جزء في الدراسات؟': 'التاريخ القديم بقى سهل لو ركزت!',
        'كيف أذاكر الاقتصاد؟': 'شوف الأرقام والجداول، هتبقى واضح!',
        'هل الجغرافيا مهمة؟': 'ايوه، مهمة جدًا لفهم البلاد!',
        'فين دروس نصف السنة؟': 'في قسم المواد تحت الدراسات!',
        'كيف أحل المسائل؟': 'اقرأ السؤال بعناية وحل خطوة بخطوة!',
        'إيه أفضل وقت للدراسة؟': 'الصبح بقى الأفضل، جرب يا صديق!',
        'هل فيه فيديوهات تعليمية؟': 'ايوه، فيه فيديوهات في قسم المواد!',
        'كيف أعرف مواعيدي؟': 'تابع قسم الاعلانات يا بطل!',
        'فين اختبارات السنة؟': 'في قسم الاختبارات تحت الدراسات!',
        'كيف أفهم الخرائط؟': 'شوف الفيديوهات وارسم بنفسك!',
        'هل الدراسات تحتاج مراجعة؟': 'ايوه، المراجعة مهمة جدًا!',
        'فين دروس الاقتصاد؟': 'في قسم المواد تحت الدراسات!',
        'كيف أحسن ذاكرتي؟': 'كرر الملخصات يوميًا يا زعيم!',
        'إيه أهم مادة؟': 'الدراسات كلها مهمة، لكن ركز على التاريخ!',
        'هل فيه مساعدة؟': 'ايوه، اسأل في الشات وهنساعدك!',
        'كيف أذاكر الجغرافيا؟': 'ركز على الخرائط والملخصات!',
        'فين دروس التاريخ القديم؟': 'في قسم المواد تحت الدراسات!',
        'متي الامتحانات النهائية؟': 'النهائية يوم 20 مايو، استعد!',
        'كيف أحل أسئلة التاريخ؟': 'اكتب الإجابات وكررها!',
        'هل الاقتصاد سهل؟': 'مع المراجعة هيبقى سهل يا صديق!',
        'فين الملخصات الشهرية؟': 'في قسم المواد تحت الدراسات!'
      },
      en: {
        'What are the key topics in studies?': 'The key topics are history and geography, focus on them, champ!',
        'How do I study studies?': 'Divide the syllabus into parts and revise daily, you’ll ace it!',
        'Where are the studies summaries?': 'Summaries are in the Materials section under Studies!',
        'When is the studies exam?': 'The studies exam is on May 15th at 10 AM!',
        'What’s the hardest part in studies?': 'Geography can be tricky, but revision makes it easy!',
        'How do I understand history?': 'Read the stories and connect events, you’ll get it, pro!',
        'Where are past studies questions?': 'In the Quizzes section under past papers!',
        'Are there videos for studies?': 'Yes, there are explanation videos in Materials!',
        'How do I improve my studies grades?': 'Solve lots of questions and join live lessons!',
        'What’s the best book for studies?': 'The official syllabus book is the best, use it, hero!',
        'When are studies lessons available?': 'Lessons are daily in the Materials section!',
        'Where are geography maps?': 'Maps are in the Studies section under Geography!',
        'How do I study wars?': 'Write a summary for each war and revise, you’ll remember!',
        'Is there an online studies exam?': 'Yes, follow the schedule for online exams!',
        'What’s the importance of studies?': 'Studies teach you your country’s history, super important, mate!',
        'How do I solve geography questions?': 'Focus on maps and revise daily!',
        'Where are history lessons?': 'In the Materials section under Studies!',
        'When are live studies lessons?': 'Live lessons start at 8 PM!',
        'How do I understand economics?': 'Watch videos and use summaries, it’ll clear up!',
        'Are studies hard?': 'Not everyone finds them easy, but effort makes it so!',
        'Where are mid-term exams?': 'In the Quizzes section under Studies!',
        'How do I prep for the final exam?': 'Revise all summaries and do practice tests!',
        'What’s the best way for maps?': 'Draw them yourself, you’ll remember better!',
        'Where are geography lessons?': 'In the Materials section under Studies!',
        'How do I improve my writing in studies?': 'Write short, clear answers!',
        'Are there extra books?': 'Yes, check the Materials section!',
        'When are studies results out?': 'Results are out after grading in Results!',
        'How do I prepare for the exam?': 'Use summaries and practice tests!',
        'Where are answer examples?': 'In the Quizzes section under Studies!',
        'What’s the easiest part in studies?': 'Ancient history gets easy with focus!',
        'How do I study economics?': 'Look at numbers and tables, it’ll click!',
        'Is geography important?': 'Yes, very important to understand countries!',
        'Where are mid-term lessons?': 'In the Materials section under Studies!',
        'How do I solve problems?': 'Read carefully and solve step by step!',
        'What’s the best study time?': 'Morning is best, try it, friend!',
        'Are there tutorial videos?': 'Yes, in the Materials section!',
        'How do I know my schedule?': 'Check the Announcements section, champ!',
        'Where are yearly exams?': 'In the Quizzes section under Studies!',
        'How do I understand maps?': 'Watch videos and draw yourself!',
        'Do studies need revision?': 'Yes, revision is super important!',
        'Where are economics lessons?': 'In the Materials section under Studies!',
        'How do I boost my memory?': 'Revise summaries daily, boss!',
        'What’s the most important subject?': 'All studies are key, but focus on history!',
        'Is there help available?': 'Yes, ask in the chat and we’ll help!',
        'How do I study geography?': 'Focus on maps and summaries!',
        'Where are ancient history lessons?': 'In the Materials section under Studies!',
        'When are final exams?': 'Finals are on May 20th, get ready!',
        'How do I answer history questions?': 'Write answers and revise them!',
        'Is economics easy?': 'With revision, it gets easy, mate!',
        'Where are monthly summaries?': 'In the Materials section under Studies!'
      }
    },
    virtualClassSkills: {
      ar: {
        'كيف أدخل الفصل الافتراضي؟': 'اضغط على رابط الفصل في قسم الإعلانات وادخل باسمك، سهلة يا بطل!',
        'إيه أفضل طريقة أشارك في الفصول؟': 'افتح الكاميرا وشارك بصوتك، خليك نشيط يا زعيم!',
        'إزاي أرفع إيدي في الفصل؟': 'ابحث عن زر رفع الإيد في الأدوات، اضغط عليه واستنى دورك!',
        'كيف أشارك شاشتي؟': 'اضغط على زر مشاركة الشاشة واختار اللي عايز تعرضه، تمام كده!',
        'إيه أعمل لو الصوت مش شغال؟': 'تأكد من المايك بتاعك، وجرب تغيّر الإعدادات من الأدوات!',
        'كيف أسجل الفصل؟': 'لو متاح، اضغط على زر التسجيل في الأدوات، بس اسأل المعلم الأول!',
        'إزاي أكتم صوتي؟': 'اضغط على زر المايك لتكتم نفسك، عشان محدش يتضايق!',
        'كيف أكتب ملاحظات أثناء الفصل؟': 'افتح برنامج ملاحظات على جهازك واكتب، أو استخدم أداة الملاحظات لو موجودة!',
        'إيه أعمل لو الفيديو بيقطع؟': 'تأكد من النت بتاعك، وقلل البرامج المفتوحة، هيبقى أحسن كده!',
        'كيف أشارك في الدردشة؟': 'ابحث عن زر الدردشة واكتب رسالتك، خليك واضح يا صديق!',
        'إزاي أحمل ملفات الفصل؟': 'اضغط على زر الملفات واختار تحميل، هيبقوا عندك فورًا!',
        'كيف أعرف مواعيد الفصول؟': 'شوف قسم الإعلانات، المواعيد هناك، تابعها يا أستاذ!',
        'إيه أعمل لو ما عرفتش أدخل؟': 'جرب رابط جديد أو تواصل مع الدعم، احنا معاك!',
        'كيف أستخدم السبورة البيضاء؟': 'اضغط على أداة السبورة وارسم أو اكتب، ممتعة جدًا!',
        'إزاي أكون نشيط في الفصل؟': 'اسأل أسئلة وشارك في النقاش، خليك مميز يا نجم!'
      },
      en: {
        'How do I join a virtual class?': 'Click the class link in Announcements and enter with your name, easy peasy, champ!',
        'What’s the best way to participate in classes?': 'Turn on your camera and speak up, stay active, boss!',
        'How do I raise my hand in class?': 'Look for the raise hand button in the tools, click it and wait for your turn!',
        'How do I share my screen?': 'Click the share screen button and pick what you wanna show, you’re good!',
        'What if the audio isn’t working?': 'Check your mic, and try adjusting settings from the tools!',
        'How do I record the class?': 'If allowed, click the record button in tools, but ask the teacher first!',
        'How do I mute myself?': 'Click the mic button to mute, so no one gets annoyed!',
        'How do I take notes during class?': 'Open a notes app on your device and write, or use the notes tool if available!',
        'What if the video keeps lagging?': 'Check your internet, and close other apps, it’ll get better!',
        'How do I use the chat in class?': 'Find the chat button and type your message, be clear, mate!',
        'How do I download class files?': 'Click the files button and select download, they’ll be with you right away!',
        'How do I know class schedules?': 'Check the Announcements section, schedules are there, stay on top, pro!',
        'What if I can’t join the class?': 'Try a new link or contact support, we’ve got you!',
        'How do I use the whiteboard?': 'Click the whiteboard tool and draw or write, it’s super fun!',
        'How can I be active in class?': 'Ask questions and join discussions, stand out, star!'
      }
    }
  };